version: '3.8'
services:
  webapp:
    image: ask-my-docs:poc
    build:
      context: .
      dockerfile: Dockerfile
    #env_file: .env
    container_name: ask-my-docs
    ports:
      - "8501:8501"
    volumes:
      - db-vol:/app/db
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    command: streamlit run app.py --server.enableCORS true
    init: true

volumes:
  db-vol:
